apiVersion: v2
name: chart
description: Archives Online, an application supporting discovery of archival materials, based on ArcLight
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
  - name: mysql
    version: 11.1.15
    repository: https://charts.bitnami.com/bitnami