Layout/IndentationWidth:
  Width: 2

AllCops:
  NewCops: disable
  TargetRubyVersion: 3
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
