Layout/IndentationWidth:
  Width: 2

Style/Documentation:
  Enabled: false

AllCops:
  NewCops: disable
  TargetRubyVersion: 3
  DisplayCopNames: true
  SuggestExtensions: false
  Exclude:
    - 'db/**/*'
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'lib/generators/arclight/templates/**/*'
    - 'lib/tasks/index.rake'
    - 'README.md'
    - 'app/components/blacklight_range_limit/range_form_component.rb'

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*.rake'
    - 'test/**/*'
    - 'app/controllers/catalog_controller.rb'
    - 'config/environments/development.rb'

Metrics/ClassLength:
  Exclude:
    - 'app/controllers/catalog_controller.rb'

Layout/LineLength:
  Exclude:
    - 'config/initializers/devise.rb'
    - 'lib/arclight/traject/ead2_config.rb'
    - 'lib/arclight/traject/ead2_component_config.rb'
