# Requires Docker Compose v2
name: archives_online
services:
  app:
    build:
      context: .
    image: ghcr.io/iublibtech/archives_online/archives_online:latest
    env_file:
      - .docker.env
    volumes:
      - .:/app/webapp
      - node_modules:/app/webapp/node_modules
      - ./tmp:/app/webapp/tmp
      - ./public:/app/webapp/public
      - ./generate-init.sh:/app/webapp/generate-init.sh
    depends_on:
      - db
      - solr
    ports:
      - 3000:3000
    expose:
      - 3000
    command: bundle exec puma -b tcp://0.0.0.0:3000

  db:
    platform: linux/amd64
    image: mysql:8.4.2
    env_file:
      - .docker.env
    expose:
      - 3306
    volumes:
      - db:/var/lib/mysql
      # - ./generate-init.sh:/docker-entrypoint-initdb.d/generate-init.sh

  solr:
    image: solr:8.11
    env_file:
      - .docker.env
    command: solr-precreate archives_online /opt/solr/server/configsets/arclight
    volumes:
      - solr_home:/var/solr/data
      - ./solr/conf:/opt/solr/server/configsets/arclight:ro
    ulimits:
      nofile:
        soft: 65536
        hard: 524288

volumes:
  db:
  node_modules:
  public:
  solr_home:
  tmp:
  zk:
  zoo:
