default: &default
  adapter: <%= ENV['DATABASE_ADAPTER'] || 'mysql2' %>
  host: <%= ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%= ENV['DATABASE_USER'] || 'indiana_arclight' %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
  database: <%= ENV['DATABASE_NAME'] || 'indiana_arclight' %>
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default

test:
  <<: *default
  database: <%= ENV['TEST_DB'] || 'indiana_arclight_test' %>

staging:
  <<: *default

production:
  <<: *default