name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_step:
        required: false
        description: 'Pause the selected step to debug using tmate'
        type: choice
        default: ''
        options:
          - ''
          - build
          - test
          - lint
jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@v0.0.24
    secrets: inherit
    with:
      platforms: "linux/amd64"
      baseTarget: base
      webTarget: web

  test:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@v0.0.24
    with:
      confdir: '/home/app/webapp/solr/conf'
      rspec_cmd: "cd .. && gem install semaphore_test_boosters && bundle && rspec_booster --job $CI_NODE_INDEX/$CI_NODE_TOTAL"
      setup_db_cmd: >-
        echo 'Waiting for mysql:3306...' &&
        while ! nc -z mysql 3306; do echo 'Waiting...'; sleep 1; done &&
        echo 'MySQL is up, running default setup...' &&
        RAILS_ENV=test bundle exec rake db:create db:schema:load db:migrate

  lint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v0.0.24
    with:
      webTarget: web