name: "Build Test Lint"
run-name: Build Test Lint of ${{ github.ref_name }} by @${{ github.actor }}
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
jobs:
  build:
    uses: notch8/actions/.github/workflows/build.yaml@v0.0.24
    secrets: inherit
    with:
      platforms: "linux/amd64"
      baseTarget: base
      webTarget: web

  test:
    needs: build
    uses: notch8/actions/.github/workflows/test.yaml@v0.0.24
  lint:
    needs: build
    uses: notch8/actions/.github/workflows/lint.yaml@v0.0.24
    with:
      webTarget: web